import {Controller} from '../core/controller';
import {SUBJECTS,dueReviews,confirmationAccuracy,formatTime,publicQuestion} from '../core/domain';
import type {Question,Tab} from '../core/types';
import {box,button,code,dark,light,progress,row,table,text,type Node,type Palette,type Style} from './nodes';
import {pretendardLicense} from './font-license';

export function render(c:Controller):Node {
  const p:Palette=c.isDark?dark:light;
  const onBlue=c.isDark?'#0B1220':'#FFFFFF';
  const small=(v:string,s:Style={})=>text(v,{fontSize:13,lineHeight:20,color:p.muted,...s});
  const body=(v:string,s:Style={})=>text(v,{fontSize:16,lineHeight:25,color:p.ink,...s});
  const heading=(v:string,n=28)=>({...text(v,{fontSize:n,lineHeight:n+9,fontWeight:'700',color:p.ink}),heading:true});
  const card=(children:Node[],s:Style={})=>box(children,{backgroundColor:p.surface,borderWidth:1,borderColor:p.line,borderRadius:18,padding:18,gap:12,...s});
  const primary=(v:string,fn:()=>void|Promise<void>,id?:string,disabled=false)=>button(v,fn,{backgroundColor:p.blue,color:onBlue,minHeight:52,borderRadius:14,fontWeight:'700',fontSize:16},{testId:id,disabled:disabled||c.busy});
  const secondary=(v:string,fn:()=>void|Promise<void>,id?:string)=>button(v,fn,{backgroundColor:p.surface,color:p.blue,borderWidth:1,borderColor:p.line,minHeight:48,borderRadius:12,fontWeight:'600'},{testId:id,disabled:c.busy});
  const pill=(v:string,color=p.blue,bg=p.blueSoft)=>box([text(v,{fontSize:12,fontWeight:'700',color})],{backgroundColor:bg,paddingHorizontal:10,paddingVertical:5,borderRadius:8,alignSelf:'flex-start'});
  const notice=(v:string,color=p.blue,bg=p.blueSoft)=>box([text(v,{fontSize:13,lineHeight:21,color})],{backgroundColor:bg,padding:13,borderRadius:12});
  const empty=(t:string,d:string)=>card([heading(t,20),body(d)],{paddingVertical:28});
  const brand=()=>row([box([text('S',{fontSize:22,fontWeight:'800',color:'#FFFFFF'})],{width:42,height:42,backgroundColor:'#2457D6',borderRadius:13,alignItems:'center',justifyContent:'center'}),box([text('SQLD Pass',{fontSize:19,fontWeight:'800',color:p.ink}),small('30일 SQLD 학습 루틴',{fontSize:10})],{gap:2})]);
  const question=(q:Question):Node[]=>{const pub=publicQuestion(q);return [pill(pub.subject==='S1'?'1과목':'2과목'),body(pub.stem,{fontSize:18,lineHeight:29,fontWeight:'600'}),...pub.tables.flatMap(t=>[small(t.name,{fontWeight:'700'}),table(t.columns,t.rows,t.name)]),...(pub.sql?[code(pub.sql)]:[])];};
  const choices=(q:Question,selected:string|null,submitted:boolean,choose:(id:string)=>void|Promise<void>)=>q.options.map(o=>{const ok=submitted&&o.id===q.answer,bad=submitted&&selected===o.id&&!ok,sel=selected===o.id;return button('',()=>choose(o.id),{backgroundColor:ok?p.greenSoft:bad?p.redSoft:sel?p.blueSoft:p.surface,borderWidth:1.5,borderColor:ok?p.green:bad?p.red:sel?p.blue:p.line,borderRadius:14,padding:13,alignItems:'stretch'},{label:`${o.id}번 ${o.text}`,testId:`option-${o.id}`,disabled:submitted||c.busy,selected:sel,children:[row([text(ok?'✓':bad?'×':o.id,{fontWeight:'800',color:ok?p.green:bad?p.red:sel?p.blue:p.muted}),box([o.format==='sql'?code(o.text):body(o.text,{fontSize:15})],{flex:1})],{alignItems:'flex-start'})]});});
  const explanation=(q:Question,selected?:string):Node[]=>[notice(selected===q.answer?'정답입니다.':'해설로 오개념을 확인해 보세요.',selected===q.answer?p.green:p.orange,selected===q.answer?p.greenSoft:p.orangeSoft),heading('정답 해설',20),body(q.explanation),...Object.entries(q.optionExplanations).filter(([id])=>id!==q.answer).map(([id,v])=>card([small(`${id}번 보기`,{fontWeight:'700'}),body(v,{fontSize:14})],{padding:13}))];

  let title='';let contents:Node[]=[];let footer:Node|undefined;const route=c.route.name;const s=c.state;const active=c.activeExam();const main=['home','catalog','review','exams','stats'].includes(route);
  if(!c.ready){contents=c.startupError?[empty('학습 콘텐츠를 준비하지 못했어요',c.startupError),secondary('다시 읽기',()=>c.initialize())]:[empty('학습 자료 준비 중','기기에 포함된 콘텐츠를 확인하고 있습니다.')];}
  else switch(route){
    case 'welcome': contents=[brand(),pill('회원가입 없이 · 기기 저장'),heading('오늘의 공부를\n합격의 루틴으로.'),body('이론부터 오답 복습, 90분 실전 모의고사까지 하나의 흐름으로 공부합니다.'),notice('현재 콘텐츠는 독립 감수 전 내부 테스트 원고입니다.',p.orange,p.orangeSoft),primary('SQLD 학습 시작',()=>c.navigate({name:'setup'}),'start')];break;
    case 'setup': title='학습 설정';contents=[heading('하루 학습량을 정해요.'),row([15,30,45,60,90].map(n=>button(`${n}분`,()=>{c.draftSettings.minutes=n;c.notify();},{flex:1,minHeight:48,borderRadius:10,backgroundColor:c.draftSettings.minutes===n?p.blueSoft:p.surface,color:p.ink})),{flexWrap:'wrap'}),{kind:'input',label:'목표 시험일',value:c.draftSettings.targetDate,onChange:v=>{c.draftSettings.targetDate=v;c.notify();},placeholder:'목표일 선택 · YYYY-MM-DD',style:{minHeight:52,borderWidth:1,borderColor:p.line,borderRadius:12,padding:14,color:p.ink}},primary('30일 플랜 시작',()=>c.saveSettings(true),'finish-setup')];break;
    case 'home':{const d=c.currentDay(),due=dueReviews(s,c.content,c.services.clock().wall);contents=[brand(),heading(`Day ${d.day}. 오늘 할 일을\n한 번에 끝내요.`),card([row([box([small('30일 진행'),heading(`${s.completedDays.length}/30`,24)],{flex:1}),pill(`${Math.round(s.completedDays.length/30*100)}%`)]),progress(s.completedDays.length/30,p.blue),primary(d.examId?'오늘의 모의고사 보기':'오늘의 학습 시작',()=>d.examId?c.navigate({name:'examIntro',id:d.examId??undefined}):c.navigate({name:'plan'}))]),row([card([small('오늘 복습'),heading(`${due.length}문제`,22)],{flex:1}),card([small('이론 읽음'),heading(`${s.readLessons.length}/60`,22)],{flex:1})]),...(active?[notice(`${active.title} 진행 중 · ${formatTime(c.remaining())}`,p.orange,p.orangeSoft),primary('모의고사 이어하기',()=>{c.stack=[];c.route={name:'exam',id:active.id};c.notify();})]:[]),secondary('30일 학습 플랜',()=>c.navigate({name:'plan'})),secondary('내 학습 통계',()=>c.navigate({name:'stats'}))];break;}
    case 'plan': title='30일 학습 플랜';contents=[heading('하루씩 완성하는\n30일 로드맵'),...c.content.days.map(d=>card([row([pill(`DAY ${d.day}`,s.completedDays.includes(d.day)?p.green:p.blue,s.completedDays.includes(d.day)?p.greenSoft:p.blueSoft),box([text(d.task,{fontSize:16,fontWeight:'700',color:p.ink}),small(d.examId?'실전 모의고사':`${d.lessonIds.length}개 이론 · 약 ${d.minutes}분`)],{flex:1})]),...(d.lessonIds[0]?[secondary('이론 열기',()=>c.navigate({name:'lesson',id:d.lessonIds[0]}))]:[]),...(d.examId?[secondary('모의고사 열기',()=>c.navigate({name:'examIntro',id:d.examId??undefined}))]:[])],{padding:14}))];break;
    case 'catalog':{title='학습';const list=c.content.lessons.filter(l=>(c.subject==='all'||l.subject===c.subject)&&(c.search===''||l.title.toLowerCase().includes(c.search.toLowerCase())));contents=[heading('60개 이론을\n필요한 순서로.'),{kind:'input',label:'이론 검색',value:c.search,onChange:v=>c.setSearch(v),placeholder:'예: 조인, NULL, 정규화',style:{minHeight:52,borderWidth:1,borderColor:p.line,borderRadius:12,padding:14,color:p.ink}},...list.map(l=>secondary(`${String(l.order).padStart(2,'0')} · ${l.title}${s.readLessons.includes(l.id)?' · 읽음':''}`,()=>c.navigate({name:'lesson',id:l.id}),`lesson-${l.id}`))];break;}
    case 'lesson':{title='이론';const l=c.content.lessons.find(x=>x.id===c.route.id);if(!l){contents=[empty('이론을 찾지 못했어요','학습 목록에서 다시 선택해 주세요.')];break;}contents=[pill(`LESSON ${String(l.order).padStart(2,'0')}`),heading(l.title),card([small('학습 목표',{fontWeight:'700'}),...l.objectives.map(v=>body(`✓ ${v}`,{fontSize:15}))],{backgroundColor:p.blueSoft,borderWidth:0}),body(l.body),...(l.example?[heading('예제',20),...l.example.tables.flatMap(t=>[small(t.name,{fontWeight:'700'}),table(t.columns,t.rows,t.name)]),code(l.example.sql),...(l.example.columns.length?[table(l.example.columns,l.example.rows,'예상 결과')]:[])]:[]),card([heading('핵심 요약',20),...l.summary.map(v=>body(`✓ ${v}`,{fontSize:15}))]),secondary(s.bookmarks.includes(l.id)?'★ 북마크 해제':'☆ 북마크',()=>c.bookmark(l.id)),secondary(s.readLessons.includes(l.id)?'✓ 읽음 기록됨':'이론 읽음 기록',()=>c.markLesson(l.id)),primary('확인 문제 풀기',()=>c.beginPractice(l.questionIds))];break;}
    case 'practice':{title='문제 풀이';const pr=s.practice;if(!pr){contents=[empty('진행 중인 연습이 없어요','학습 또는 복습에서 시작해 주세요.')];break;}const q=c.getQuestion(pr.questionIds[pr.index]);if(!q){contents=[empty('문항을 찾지 못했어요','연습을 다시 시작해 주세요.')];break;}contents=[small(`${pr.index+1}/${pr.questionIds.length}`),progress((pr.index+1)/pr.questionIds.length,p.blue),...question(q),...choices(q,pr.selected,pr.submitted,id=>c.selectPractice(id)),...(pr.submitted?explanation(q,pr.selected??undefined):[secondary(pr.uncertain?'✓ 확신 부족 표시됨':'? 확신 부족',()=>c.uncertain()),primary('정답 확인',()=>c.answerPractice(),'submit-practice',!pr.selected)]),...(pr.submitted?[primary(pr.index===pr.questionIds.length-1?'연습 완료':'다음 문제',()=>c.nextPractice())]:[])];break;}
    case 'review':{title='복습';const due=dueReviews(s,c.content,c.services.clock().wall);contents=[heading('틀린 이유를\n기억으로 바꿔요.'),card([small('오늘 복습'),heading(`${due.length}문제`,22)]),primary('오늘의 복습 시작',()=>c.beginDueReview(),'start-review',due.length===0),...(due.length?due.slice(0,8).map(id=>{const q=c.getQuestion(id);return q?card([small(q.subject==='S1'?'1과목':'2과목'),body(q.stem,{fontSize:14})]):box([]);}):[empty('오늘 복습할 문제가 없어요','새 학습을 진행하면 복습 일정이 만들어집니다.')])];break;}
    case 'exams': title='모의고사';contents=[heading('50문항 · 90분\n실전처럼 연습해요.'),...c.content.exams.map(e=>{const latest=[...s.exams].reverse().find(a=>a.examId===e.id);return card([row([box([heading(e.title,20),small('50문항 · 90분')],{flex:1}),pill(latest?.status==='active'?'진행중':latest?.status==='submitted'?'완료':'미응시')]),latest?.status==='active'?primary('이어하기',()=>{c.route={name:'exam',id:latest.id};c.stack=[];c.notify();}):latest?.status==='submitted'?secondary(`${latest.score?.points??0}점 결과 보기`,()=>c.navigate({name:'result',id:latest.id})):primary('시험 안내',()=>c.navigate({name:'examIntro',id:e.id}))]);})];break;
    case 'examIntro':{title='모의고사 안내';const e=c.content.exams.find(x=>x.id===c.route.id);contents=e?[heading(e.title),card([body('50문항 · 90분\n1과목 10문항 / 2과목 40문항\n미응답 0점 · 제출 후 변경 불가')]),notice('앱을 나가도 시험 시간은 계속 흐릅니다.',p.orange,p.orangeSoft),primary('실전 시작',()=>c.beginExam(e.id))]:[empty('시험을 찾지 못했어요','모의고사 목록으로 돌아가 주세요.')];break;}
    case 'exam':{title='모의고사';const e=c.examAttempt(c.route.id)??active;if(!e||e.status!=='active'){contents=[empty('진행 중 시험이 없어요','모의고사 목록에서 시작해 주세요.')];break;}const q=e.snapshots[e.index];contents=[row([pill(`${e.index+1}/50`),box([small('남은 시간'),text(formatTime(c.remaining()),{fontSize:22,fontWeight:'800',color:p.ink})],{flex:1,alignItems:'flex-end'})]),...question(q),...choices(q,e.answers[q.id]??null,false,id=>c.updateExamAnswer(id)),secondary(e.flagged.includes(q.id)?'◆ 보류 해제':'◇ 보류',()=>c.flagExam()),row([secondary('← 이전',()=>c.moveExam(e.index-1)),secondary('답안표',()=>c.navigate({name:'sheet',id:e.id})),primary(e.index===49?'제출 검토':'다음 →',()=>e.index===49?c.navigate({name:'sheet',id:e.id}):c.moveExam(e.index+1))],{flexWrap:'wrap'})];break;}
    case 'sheet':{title='답안표';const e=c.examAttempt(c.route.id)??active;if(!e){contents=[empty('시험 기록이 없어요','모의고사 목록으로 돌아가 주세요.')];break;}contents=[heading('답안 빠른 이동',20),row(e.snapshots.map((q,i)=>button(String(i+1),()=>c.moveExam(i),{width:48,height:48,borderRadius:10,borderWidth:1,borderColor:e.flagged.includes(q.id)?p.orange:p.line,backgroundColor:e.answers[q.id]?p.blueSoft:p.surface,color:p.ink},{testId:`sheet-${i+1}`})),{flexWrap:'wrap'}),notice(`응답 ${Object.keys(e.answers).length} · 미응답 ${50-Object.keys(e.answers).length} · 보류 ${e.flagged.length}`),primary('최종 제출',()=>c.requestSubmit())];break;}
    case 'result':{title='모의고사 결과';const e=c.examAttempt(c.route.id);if(!e||e.status!=='submitted'||!e.score){contents=[empty('결과가 없어요','시험을 제출한 뒤 확인할 수 있습니다.')];break;}contents=[heading('결과를 다음 공부에\n연결해요.'),card([small('총점 · 앱 내부 연습 기준'),text(`${e.score.points} / 100`,{fontSize:42,fontWeight:'800',color:p.blue}),small(`정답 ${e.score.correct} · 미응답 ${e.score.unanswered}`)]),...(['S1','S2'] as const).map(id=>card([text(SUBJECTS[id],{fontSize:16,fontWeight:'700',color:p.ink}),text(`${e.score!.bySubject[id].points}/${e.score!.bySubject[id].max}점`,{fontSize:20,fontWeight:'700',color:p.ink}),progress(e.score!.bySubject[id].points/e.score!.bySubject[id].max,p.blue)])),notice('실제 시험 합격 확률이나 공식 합격 판정이 아닙니다.',p.orange,p.orangeSoft),primary('정답·해설 보기',()=>c.navigate({name:'examReview',id:e.id,index:0})),secondary('모의고사 목록',()=>c.tab('exams'))];break;}
    case 'examReview':{title='정답·해설';const e=c.examAttempt(c.route.id);if(!e||e.status!=='submitted'){contents=[empty('제출 후 확인할 수 있어요','시험을 먼저 제출해 주세요.')];break;}const i=Math.min(49,Math.max(0,c.route.index??0)),q=e.snapshots[i];contents=[small(`${i+1}/50`),...question(q),...choices(q,e.answers[q.id]??null,true,()=>{}),...explanation(q,e.answers[q.id])];footer=row([secondary('← 이전',()=>{c.route={...c.route,index:Math.max(0,i-1)};c.notify();}),primary(i===49?'결과로':'다음 →',()=>{c.route=i===49?{name:'result',id:e.id}:{...c.route,index:i+1};c.notify();})]);break;}
    case 'stats':{title='내 학습';const a=confirmationAccuracy(s,c.content);contents=[heading('학습 기록'),row([card([small('학습 날짜'),heading(`${s.studyDays.length}일`,22)],{flex:1}),card([small('최초·확신 정답률'),heading(a.confidentPercent===null?'—':`${a.confidentPercent}%`,22)],{flex:1})]),row([card([small('이론 읽음'),heading(`${s.readLessons.length}/60`,22)],{flex:1}),card([small('모의고사 제출'),heading(`${s.exams.filter(e=>e.status==='submitted').length}회`,22)],{flex:1})]),secondary('설정',()=>c.navigate({name:'settings'})),secondary('고객센터',()=>c.navigate({name:'help'})),secondary('콘텐츠 상태',()=>c.navigate({name:'notices'})),secondary('개인정보 안내',()=>c.navigate({name:'privacy'}))];break;}
    case 'settings': title='설정';contents=[heading('학습 환경'),notice('현재 로그인·광고·원격 분석·결제가 없습니다.'),secondary('라이트 모드',async()=>{c.draftSettings.theme='light';await c.commit(x=>({...x,settings:{...x.settings,theme:'light'}}));}),secondary('다크 모드',async()=>{c.draftSettings.theme='dark';await c.commit(x=>({...x,settings:{...x.settings,theme:'dark'}}));}),secondary('이 앱 학습 데이터 초기화',()=>c.requestReset())];break;
    case 'help': title='고객센터';contents=[heading('오류·의견 제보'),body('학습 답안이나 개인정보를 자동 전송하지 않습니다.'),{kind:'input',label:'오류 상황',value:c.supportText,onChange:v=>{c.supportText=v;c.notify();},placeholder:'어느 화면에서 어떤 문제가 있었나요?',multiline:true,style:{minHeight:120,borderWidth:1,borderColor:p.line,borderRadius:12,padding:14,color:p.ink}},...(c.services.supportEmail?[body(c.services.supportEmail),primary('이메일로 문의하기',()=>c.contactSupport(),'support-email')]:[]),...(c.services.supportUrl?[secondary('고객지원 페이지',()=>c.external(c.services.supportUrl!),'support-page')]:[]),secondary('제보 내용 공유하기',()=>c.report(c.route.id))];break;
    case 'notices': title='콘텐츠 상태';contents=[heading('내장 콘텐츠'),notice(c.content.manifest.note,p.orange,p.orangeSoft),body('이론 60개 · 확인 문제 120개 · 모의고사 20회 · 1,000문항'),heading('오픈소스 글꼴',20),body('Pretendard 1.3.9 · 길형진\nSIL Open Font License 1.1'),secondary(c.expanded.has('font-license')?'글꼴 라이선스 접기':'글꼴 라이선스 전문',()=>c.toggleExpanded('font-license'),'font-license'),...(c.expanded.has('font-license')?[body(pretendardLicense,{fontSize:13,lineHeight:21})]:[])];break;
    case 'privacy': title='개인정보 안내';contents=[heading('공부 기록은 기기에.'),body('목표, 이론 읽음, 북마크, 문제 선택, 복습 일정과 모의고사 결과는 SQLD Pass 전용 SQLite에 저장합니다.'),...(c.services.privacyUrl?[primary('개인정보처리방침 전문',()=>c.external(c.services.privacyUrl!),'privacy-policy')]:[notice('정식 배포 전 개인정보처리방침과 운영 연락처를 확정해야 합니다.',p.orange,p.orangeSoft)])];break;
    default: contents=[empty('준비 중인 화면입니다','이전 화면으로 돌아가 주세요.')];
  }

  const header=(!c.ready||route==='welcome')?undefined:row([...(main?[brand()]:[button('‹',()=>c.back(),{width:48,minHeight:48,fontSize:30,color:p.ink},{label:'뒤로'}),text(title,{fontSize:18,fontWeight:'700',color:p.ink,flex:1})]),...(main?[box([],{flex:1}),button('◉',()=>c.navigate({name:'stats'}),{width:48,minHeight:48,borderRadius:14,backgroundColor:p.blueSoft,color:p.blue},{label:'내 학습'})]:[])],{paddingHorizontal:16,paddingVertical:8,borderBottomWidth:1,borderColor:p.line,backgroundColor:p.surface});
  const tabs:[Tab,string][]=[['today','홈'],['learn','학습'],['exams','실전'],['records','기록']];const selected:Record<string,Tab>={home:'today',catalog:'learn',review:'learn',exams:'exams',stats:'records'};
  if(main&&c.ready)footer=row(tabs.map(([id,label])=>button(`${({today:'⌂',learn:'▤',exams:'◷',records:'▥',review:'▤'} as const)[id]}\n${label}`,()=>c.tab(id),{flex:1,minHeight:58,borderRadius:12,backgroundColor:selected[route]===id?p.blueSoft:p.surface,color:selected[route]===id?p.blue:p.muted,fontSize:12,fontWeight:'700'},{label,testId:`tab-${id}`,role:'tab',selected:selected[route]===id})),{backgroundColor:p.surface,padding:10,borderTopWidth:1,borderColor:p.line,gap:5});
  const content=box([...(c.notice?[notice(c.notice)]:[]),...contents],{paddingHorizontal:20,paddingTop:22,paddingBottom:36,gap:17},`${route}:${c.route.id??''}:${c.route.index??''}:${s.practice?.index??''}`);content.scroll=true;
  const root=box([...(header?[header]:[]),content,...(footer?[footer]:[])],{flex:1,backgroundColor:p.bg},'app');
  if(c.dialog)root.children!.push({kind:'modal',label:c.dialog.title,close:()=>c.cancelDialog(),children:[card([heading(c.dialog.title,20),body(c.dialog.body),primary(c.dialog.confirmLabel,()=>c.acceptDialog()),secondary('취소',()=>c.cancelDialog())],{maxWidth:420,width:'100%'})]});
  return root;
}
